# Generated by Django 4.0.5 on 2022-06-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='youtube_link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
