# Generated by Django 4.0.5 on 2022-06-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_created_at_album_updated_at_song_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('podcast_title', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('podcast_logo', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
