# Generated by Django 4.0.5 on 2022-06-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_title',
            field=models.CharField(max_length=100),
        ),
    ]
